version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
        replicas: 1
        placement:
            constraints: [node.role == manager]

networks:
  default:
    external:
      name: nginx-proxy

